code --install-extension formulahendry.auto-complete-tag
code --install-extension beardedbear.beardedtheme
code --install-extension formulahendry.auto-rename-tag
code --install-extension naumovs.color-highlight
code --install-extension miguelsolorio.fluent-icons
code --install-extension golang.go
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension ritwickdey.liveserver
code --install-extension sumneko.lua
code --install-extension yzhang.markdown-all-in-one
code --install-extension christian-kohler.path-intellisense
code --install-extension esbenp.prettier-vscode
code --install-extension miguelsolorio.symbols
code --install-extension nur.just-black
code --install-extension MS-vsliveshare.vsliveshare
code --install-extension steoates.autoimport
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension dbaeumer.vscode-eslint
code --install-extension bradlc.vscode-tailwindcss
code --install-extension ms-python.python
code --install-extension ms-python.black-formatter
code --install-extension aaron-bond.better-comments
code --install-extension usernamehw.errorlens
code --install-extension yzhang.markdown-all-in-one
code --install-extension alefragnani.project-manager
code --install-extension christian-kohler.path-intellisense
